services:
  - type: web
    name: profile-number-generator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
  - type: worker
    name: profile-number-generator-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: TELEGRAM_BOT_TOKEN
        sync: false
